### ISSUE TITLE
Dogfood your Pitbull lyrics?

### ISSUE THREAD

**Issue by nixjdm** [LeviBorodenko/lancer#2]
How much better would this project be, maintained using itself? 🐶

Can you _commit_ to it?

**Comment by LeviBorodenko** [comment]
I quite like the irony of a clean codebase for lancer!

**Comment by squarebridges** [comment]
I quite like the irony of this line combined with that statement:

https://github.com/LeviBorodenko/lancer/blob/master/src/lancer/entry.py#L85

(this is a fantastic project by the way, love it)
