### ISSUE TITLE
Documentation needed on etymology

### ISSUE THREAD

**Issue by snuggie12** [LeviBorodenko/lancer#3]
Why `lancer`? Hoping for some deep lore.

I suppose others might ask "why pitbull?" but I think I understand the genius already.

**Comment by LeviBorodenko** [comment]
The origin of the name `lancer` mainly remains undocumented due to me being ashamed of it. It's rather tasteless.
It is a portmanteau of linter and cancer.

**Comment by leloup314** [comment]
According to Pitbull: ¿Why not call it `dale`? :smile:
